import("Configuration.rb")

default_platform(:ios)

platform :ios do
  configuration = Configuration.new()

  import("./scripts/build.rb")
  import("./scripts/test.rb")
  import("./scripts/analyse.rb")
  import("./scripts/deploy.rb")

  ##### PUBLIC LANES #####

  desc "Build framework for different SDKs"
  lane :build do
    configuration.sdks.defaults.each do |sdk|
      build_framework configuration: configuration, sdk: sdk
    end
  end

  desc "Build and test framework for different SDKs"
  lane :test do
    configuration.sdks.tests.each do |sdk|
      test_framework configuration: configuration, sdk: sdk
    end
  end

  desc "Analyse the test result for the framework"
  lane :analyse do
    convert_code_coverage configuration: configuration

    analyse_source_code login: ENV["SONAR_CLOUD_TOKEN"], pull_request_branch: ENV["BRANCH_NAME"], pull_request_base: ENV["CHANGE_TARGET"], pull_request_key: ENV["CHANGE_ID"]
  end

  desc "Proceed to deploy a new version of the framework for the specified environment"
  lane :deploy_artefact do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:tag]
      raise "No tag specified!".red
    end

    environment = options[:environment]
    tag = options[:tag]

    if !configuration.allowed_environments.include? environment
      raise "Wrong environment specified!".red
    end

    framework_suffix = get_framework_suffix(environment)

    # Retrieve project version
    version = get_version(environment, configuration.project.file_path, configuration.project.name, tag)

    # Make the framework
    make_artefact configuration: configuration, framework_suffix: framework_suffix, environment: environment, tag: tag, version: version

    if !options[:dry_run]
      case environment
      when "development", "devc", "staging", "prod"
        # Upload artefact to artifactory
        upload_artefact_artifactory configuration: configuration, framework_suffix: framework_suffix, environment: environment, version: version
      when "beta", "release"
        # Prepare artefact to be uploaded on S3
        prepare_amazon_artefacts configuration: configuration, framework_suffix: framework_suffix, environment: environment, version: version
      end
    end
  end

  desc "Proceed to deploy a new version of the framewok for the specified environment"
  lane :deploy_podspec do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:tag]
      raise "No tag specified!".red
    end

    environment = options[:environment]
    tag = options[:tag]

    if !configuration.allowed_environments.include? environment
      raise "Wrong environment specified!".red
    end

    framework_suffix = get_framework_suffix(environment)

    # Retrieve project version
    version = get_version(environment, configuration.project.file_path, configuration.project.name, tag)

    case environment
    when "beta"
      # Upload updated Podspec to public Cocoapods repository
      push_to_cocoapods_repository configuration: configuration, framework_suffix: framework_suffix, version: version
    when "release"
      # Upload updated Podspec to Cocoapods trunk
      # TODO: Perform initial release on Cocoapods trunk to obtain CocoaPods authentication token
      # TODO: See https://fuller.li/posts/automated-cocoapods-releases-with-ci on how to automate 'pod trunk push OguryCore.podspec.json' with CocoaPods authentication token
    end
  end
end
