import("./configuration.rb")

default_platform(:ios)

platform :ios do
  configuration = Configuration.new()

  import("./scripts/utility_functions.rb")
  import("./scripts/test.rb")
  import("./scripts/analyse.rb")
  import("./scripts/build.rb")
  import("./scripts/prepare_deploy.rb")
  import("./scripts/deploy.rb")

  lane :generate_podfile do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    environment = options[:environment]

    if !configuration.allowed_environments.include? environment
      raise "Wrong environment specified!".red
    end

    artifactory_repository_name = get_artifactory_repository_name(environment)
    framework_suffix = get_framework_suffix(environment)
    ogury_core_version = get_module_version(environment, configuration.frameworks.ogury_core.internal_version, configuration.frameworks.ogury_core.beta_version, configuration.frameworks.ogury_core.release_version)
    ogury_ads_version = get_module_version(environment, configuration.frameworks.ogury_ads.internal_version, configuration.frameworks.ogury_ads.beta_version, configuration.frameworks.ogury_ads.release_version)
    ogury_choice_manager_version = get_module_version(environment, configuration.frameworks.ogury_choice_manager.internal_version, configuration.frameworks.ogury_choice_manager.beta_version, configuration.frameworks.ogury_choice_manager.release_version)

    erb(
      template: "./fastlane/templates/Podfile.erb",
      destination: "./Podfile",
      placeholders: {
        :environment => environment,
        :framework_suffix => framework_suffix,
        :artifactory_repository_name => artifactory_repository_name,
        :ogury_core_version => ogury_core_version,
        :ogury_ads_version => ogury_ads_version,
        :ogury_choice_manager_version => ogury_choice_manager_version,
      },
    )
  end

  lane :build do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    environment = options[:environment]

    # Install Cocoapods dependencies
    update_internal_cocoapods environment: environment

    generate_podfile environment: environment

    cocoapods(
      podfile: "./Podfile",
      repo_update: true
    )

    configuration.sdks.defaults.each do |sdk|
      build_framework(
        configuration: configuration,
        sdk: sdk,
      )
    end
  end

  lane :test do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    environment = options[:environment]

    # Install Cocoapods dependencies
    update_internal_cocoapods environment: environment

    generate_podfile environment: environment

    cocoapods(
      podfile: "./Podfile",
      repo_update: true
    )

    configuration.sdks.tests.each do |sdk|
      test_framework configuration: configuration, sdk: sdk
    end
  end

  lane :analyse do
    convert_code_coverage configuration: configuration

    analyse_source_code login: ENV["SONAR_CLOUD_TOKEN"], pull_request_branch: ENV["BRANCH_NAME"], pull_request_base: ENV["CHANGE_TARGET"], pull_request_key: ENV["CHANGE_ID"]
  end

  lane :generate_test_app do
    build_test_app configuration: configuration
  end

  desc "Proceed to deploy a new version of the framewok for the specified environment"
  lane :deploy_artefact do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:tag]
      raise "No tag specified!".red
    end

    environment = options[:environment]
    tag = options[:tag]

    if !configuration.allowed_environments.include? environment
      raise "Wrong environment specified!".red
    end

    framework_suffix = get_framework_suffix(environment)

    # Retrieve project version
    version = get_version(environment, configuration.project.file_path, configuration.project.name, tag)

    # Install Cocoapods dependencies
    update_internal_cocoapods environment: environment

    generate_podfile environment: environment

    cocoapods(
      podfile: "./Podfile",
      repo_update: true
    )

    # Make the framework
    make_artefact environment: environment, version: version, tag: tag

    if !options[:dry_run]
      case environment
      when "devc", "staging", "prod"
        # Upload artefact to artifactory
        upload_artefact_artifactory configuration: configuration, framework_suffix: framework_suffix, environment: environment, version: version
      when "beta", "release"
        # Prepare artefacts that will be uploaded to amazon
        prepare_amazon_artefacts configuration: configuration, framework_suffix: framework_suffix, environment: environment, version: version
      end
    end
  end

  desc "Proceed to deploy a new version of the framewok for the specified environment"
  lane :deploy_podspec do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:tag]
      raise "No tag specified!".red
    end

    environment = options[:environment]
    tag = options[:tag]

    if !configuration.allowed_environments.include? environment
      raise "Wrong environment specified!".red
    end

    framework_suffix = get_framework_suffix(environment)

    # Retrieve project version
    version = get_version(environment, configuration.project.file_path, configuration.project.name, tag)

    case environment
    when "beta"
      # Upload updated Podspec to public Cocoapods repository
      push_to_cocoapods_repository configuration: configuration, framework_suffix: framework_suffix, version: version
    when "release"
      # Upload updated Podspec to Cocoapods trunk
      # TODO: Perform initial release on Cocoapods trunk to obtain CocoaPods authentication token
      # TODO: See https://fuller.li/posts/automated-cocoapods-releases-with-ci on how to automate 'pod trunk push OguryCore.podspec.json' with CocoaPods authentication token
    end
  end

  ##### PRIVATE LANES #####

  desc "Install cocoapods internal repository for environment and update it."
  lane :update_internal_cocoapods do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    environment = options[:environment]

    artifactory_repository_url = get_artifactory_repository_url(environment, configuration.artifactory.url)
    if !artifactory_repository_url
      next
    end

    if artifactory_repository_url.empty?
      next
    end

    artifactory_repository_name = get_artifactory_repository_name(environment)

    Dir.chdir("..") do
      sh("pod repo-art add #{artifactory_repository_name} #{artifactory_repository_url} || true")
      sh("pod repo-art update #{artifactory_repository_name}")
    end
  end

  desc "Make artefact containing the combined framework and the updated podspec"
  private_lane :make_artefact do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:version]
      raise "No version specified!".red
    end

    environment = options[:environment]
    version = options[:version]

    framework_suffix = get_framework_suffix(environment)

    # Source URL for Cocoapods
    source_url = ""

    case environment
    when "development", "devc", "staging", "prod"
      # Artifactory
      source_url = "#{configuration.artifactory.url}/sdk-cocoapods-#{environment}/#{configuration.project.public_name}#{framework_suffix}"
    when "beta", "release"
      #S3 /beta
      source_url = "#{configuration.amazon.url}/#{environment}/#{configuration.amazon.project_key}/#{version}"
    end

    # Generate the Podfile matching the selected environment and install the dependencies.
    generate_podfile environment: environment

    cocoapods(
      podfile: "./Podfile",
    )

    # Build the frameworks for multiple SDKs
    build_frameworks configuration: configuration, version: version

    # Package the framework before sending it
    combine_frameworks configuration: configuration, framework_suffix: framework_suffix

    # Update Podspec
    update_podspec(
      configuration: configuration,
      framework_suffix: framework_suffix,
      environment: environment,
      version: version,
      source_url: source_url,
    )

    create_artefact configuration: configuration, environment: environment, version: version
  end
end
