//
//  AdsCardLibraryMocks.generated.swift
//  AdsCardLibrary
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import AdsCardLibrary
@testable import Mockingbird
import Combine
import ComposableArchitecture
import Foundation
import OguryAds
import OguryAds.Private
import OguryCore
import Swift
import SwiftUI
import UIKit

private let mkbGenericStaticMockContext = Mockingbird.GenericStaticMockContext()

// MARK: - Mocked AdLifeCycleDelegate
public final class AdLifeCycleDelegateMock: AdsCardLibrary.AdLifeCycleDelegate, Mockingbird.Mock {
  typealias MockingbirdSupertype = AdsCardLibrary.AdLifeCycleDelegate
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "AdsCardLibrary"])

  fileprivate init(sourceLocation: Mockingbird.SourceLocation) {
    self.mockingbirdContext.sourceLocation = sourceLocation
    AdLifeCycleDelegateMock.mockingbirdContext.sourceLocation = sourceLocation
  }

  // MARK: Mocked `viewController`<T: AdsCardLibrary.AdManager>(forBanner `banner`: T.Ad, `adManager`: T)
  public func `viewController`<T: AdsCardLibrary.AdManager>(forBanner `banner`: T.Ad, `adManager`: T) -> UIViewController? {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`viewController`<T: AdsCardLibrary.AdManager>(forBanner `banner`: T.Ad, `adManager`: T) -> UIViewController?", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`banner`), Mockingbird.ArgumentMatcher(`adManager`)], returnType: Swift.ObjectIdentifier((UIViewController?).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (T.Ad, T) -> UIViewController? { return mkbImpl(`banner`, `adManager`) }
      if let mkbImpl = mkbImpl as? () -> UIViewController? { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: UIViewController? = mkbObject.`viewController`(forBanner: `banner`, adManager: `adManager`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (UIViewController?).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `viewController`<T: AdsCardLibrary.AdManager>(forBanner `banner`: @autoclosure () -> T.Ad, `adManager`: @autoclosure () -> T) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (T.Ad, T) -> UIViewController?, UIViewController?> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (T.Ad, T) -> UIViewController?, UIViewController?>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`viewController`<T: AdsCardLibrary.AdManager>(forBanner `banner`: T.Ad, `adManager`: T) -> UIViewController?", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`banner`), Mockingbird.resolve(`adManager`)], returnType: Swift.ObjectIdentifier((UIViewController?).self)))
  }

  // MARK: Mocked `showConsentNotice`()
  public func `showConsentNotice`() -> Void {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`showConsentNotice`() -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Void = mkbObject.`showConsentNotice`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `showConsentNotice`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`showConsentNotice`() -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  // MARK: Mocked `showImportPanel`()
  public func `showImportPanel`() -> Void {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`showImportPanel`() -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Void = mkbObject.`showImportPanel`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `showImportPanel`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`showImportPanel`() -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  // MARK: Mocked `enableTestModeForAllCards`(_ `param1`: Bool)
  public func `enableTestModeForAllCards`(_ `param1`: Bool) -> Void {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`enableTestModeForAllCards`(_ `param1`: Bool) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`param1`)], returnType: Swift.ObjectIdentifier((Void).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (Bool) -> Void { return mkbImpl(`param1`) }
      if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Void = mkbObject.`enableTestModeForAllCards`(`param1`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `enableTestModeForAllCards`(_ `param1`: @autoclosure () -> Bool) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (Bool) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (Bool) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`enableTestModeForAllCards`(_ `param1`: Bool) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`param1`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  // MARK: Mocked `share`(`json`: String, `filename`: String)
  public func `share`(`json`: String, `filename`: String) -> Void {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`share`(`json`: String, `filename`: String) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`json`), Mockingbird.ArgumentMatcher(`filename`)], returnType: Swift.ObjectIdentifier((Void).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (String, String) -> Void { return mkbImpl(`json`, `filename`) }
      if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Void = mkbObject.`share`(json: `json`, filename: `filename`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `share`(`json`: @autoclosure () -> String, `filename`: @autoclosure () -> String) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String, String) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String, String) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`share`(`json`: String, `filename`: String) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`json`), Mockingbird.resolve(`filename`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  // MARK: Mocked `deleteCard`(withId `id`: UUID)
  public func `deleteCard`(withId `id`: UUID) -> Void {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`deleteCard`(withId `id`: UUID) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`id`)], returnType: Swift.ObjectIdentifier((Void).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (UUID) -> Void { return mkbImpl(`id`) }
      if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Void = mkbObject.`deleteCard`(withId: `id`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `deleteCard`(withId `id`: @autoclosure () -> UUID) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (UUID) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (UUID) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`deleteCard`(withId `id`: UUID) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`id`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }
}

/// Returns a concrete mock of `AdLifeCycleDelegate`.
public func mock(_ type: AdsCardLibrary.AdLifeCycleDelegate.Protocol, file: StaticString = #file, line: UInt = #line) -> AdLifeCycleDelegateMock {
  return AdLifeCycleDelegateMock(sourceLocation: Mockingbird.SourceLocation(file, line))
}
