//
//  AdsCardLibraryTests-AdsCardLibraryMocks.generated.swift
//  AdsCardLibrary
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import AdsCardLibrary
@testable import Mockingbird
import Combine
import ComposableArchitecture
import Foundation
import OguryAds
import Swift
import SwiftUI
import UIKit

private let mkbGenericStaticMockContext = Mockingbird.GenericStaticMockContext()
// MARK: - Mocked AdLifeCycleDelegate
public final class AdLifeCycleDelegateMock: AdsCardLibrary.AdLifeCycleDelegate, Mockingbird.Mock {
    public func enableTestModeForAllCards(_: Bool) {
        
    }
    
    public func showConsentNotice() {
        
    }
    
    public func share(json: String, filename: String) {
        
    }
    
    public func showImportPanel() {
        
    }
    
  typealias MockingbirdSupertype = AdsCardLibrary.AdLifeCycleDelegate
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "AdsCardLibrary"])

  fileprivate init(sourceLocation: Mockingbird.SourceLocation) {
    self.mockingbirdContext.sourceLocation = sourceLocation
    AdLifeCycleDelegateMock.mockingbirdContext.sourceLocation = sourceLocation
  }

  // MARK: Mocked `viewController`<T: AdsCardLibrary.AdManager>(forBanner `banner`: T.Ad, `adManager`: T)
  public func `viewController`<T: AdsCardLibrary.AdManager>(forBanner `banner`: T.Ad, `adManager`: T) -> UIKit.UIViewController? {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`viewController`<T: AdsCardLibrary.AdManager>(forBanner `banner`: T.Ad, `adManager`: T) -> UIKit.UIViewController?", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`banner`), Mockingbird.ArgumentMatcher(`adManager`)], returnType: Swift.ObjectIdentifier((UIKit.UIViewController?).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (T.Ad, T) -> UIKit.UIViewController? { return mkbImpl(`banner`, `adManager`) }
      if let mkbImpl = mkbImpl as? () -> UIKit.UIViewController? { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: UIKit.UIViewController? = mkbObject.`viewController`(forBanner: `banner`, adManager: `adManager`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (UIKit.UIViewController?).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `viewController`<T: AdsCardLibrary.AdManager>(forBanner `banner`: @autoclosure () -> T.Ad, `adManager`: @autoclosure () -> T) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (T.Ad, T) -> UIKit.UIViewController?, UIKit.UIViewController?> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (T.Ad, T) -> UIKit.UIViewController?, UIKit.UIViewController?>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`viewController`<T: AdsCardLibrary.AdManager>(forBanner `banner`: T.Ad, `adManager`: T) -> UIKit.UIViewController?", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`banner`), Mockingbird.resolve(`adManager`)], returnType: Swift.ObjectIdentifier((UIKit.UIViewController?).self)))
  }

  // MARK: Mocked `deleteCard`(withId `id`: UUID)
  public func `deleteCard`(withId `id`: UUID) -> Void {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`deleteCard`(withId `id`: UUID) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`id`)], returnType: Swift.ObjectIdentifier((Void).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (UUID) -> Void { return mkbImpl(`id`) }
      if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Void = mkbObject.`deleteCard`(withId: `id`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `deleteCard`(withId `id`: @autoclosure () -> UUID) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (UUID) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (UUID) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`deleteCard`(withId `id`: UUID) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`id`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }
}

/// Returns a concrete mock of `AdLifeCycleDelegate`.
public func mock(_ type: AdsCardLibrary.AdLifeCycleDelegate.Protocol, file: StaticString = #file, line: UInt = #line) -> AdLifeCycleDelegateMock {
  return AdLifeCycleDelegateMock(sourceLocation: Mockingbird.SourceLocation(file, line))
}
