##########################
# Required configuration #
##########################

sonar.organization=ogury
sonar.projectKey=Ogury_sdk-ads-ios
sonar.projectName=sdk-ads-ios
# sonar.projectVersion=3.0.0 # TODO: Move this to Sonar action with automated version assignment with Jenkins
sonar.projectDescription=Display ADS

sonar.host.url=https://sonarcloud.io/
sonar.cfamily.threads=2
sonar.cfamily.cache.enabled=false

sonar.sources=Sources
sonar.tests=Tests

sonar.pullrequest.provider=GitHub
sonar.pullrequest.github.repository=Ogury/sdk-ads-ios
 
##########################
# Optional configuration #
##########################
sonar.cfamily.compile-commands=compilation-database.json
sonar.sourceEncoding=UTF-8
sonar.coverageReportPaths=jenkins/output/sonarqube-generic-coverage.xml

# Define patterns for C
sonar.lang.patterns.c=**/*.c
sonar.c.file.suffixes=-

# Define patterns for Objective-C
sonar.lang.patterns.objc=**/*.m,**/*.mm,**/*.h
sonar.cpp.file.suffixes=-
