import("./configuration.rb")
import("./scripts/test.rb")
import("./scripts/utility_functions.rb")
import("./scripts/prepare_deploy.rb")
import("./scripts/deploy.rb")
import("./scripts/build.rb")

default_platform(:ios)

platform :ios do
  configuration = Configuration.new()

  ##### PUBLIC LANES #####

  lane :build do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    environment = options[:environment]

    # Install Cocoapods dependencies
    update_internal_cocoapods environment: environment
    generate_podfile environment: environment
    artifactory = options[:artifactory] ? options[:artifactory] : false

    cocoapods(
      podfile: "./Podfile",
      repo_update: true
      )

    configuration.sdks.defaults.each do |sdk|
      build_core_framework(
        configuration: configuration,
        sdk: sdk,
        artifactory: artifactory
        )

      build_ads_framework(
        configuration: configuration,
        sdk: sdk,
        artifactory: artifactory
        )

      build_card_library(
        configuration: configuration,
        sdk: sdk,
        artifactory: artifactory
        )

      build_wrapper(
        configuration: configuration,
        sdk: sdk,
        artifactory: artifactory
        )

      # build_test_app(
      #   configuration: configuration,
      #   sdk: sdk,
      #   artifactory: artifactory
      #   )
    end
  end

  desc "Install cocoapods internal repository for environment and update it."
  lane :update_internal_cocoapods do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    environment = options[:environment]

    artifactory_repository_url = get_artifactory_repository_url(environment, configuration.artifactory.url)
    if !artifactory_repository_url
      next
    end

    if artifactory_repository_url.empty?
      next
    end

    artifactory_repository_name = get_artifactory_repository_name(environment)

    Dir.chdir("..") do
      sh("pod repo-art add #{artifactory_repository_name} #{artifactory_repository_url} || true")
      sh("pod repo-art update #{artifactory_repository_name}")
    end
  end

  desc "Generates a new Podilfe based on the environment and the configuration file"
  lane :generate_podfile do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !configuration.allowed_environments.include? options[:environment]
      raise "Wrong environment specified!".red
    end

    environment = options[:environment]
    
    artifactory_repository_name = get_artifactory_repository_name(environment)
    ogury_core_version = get_module_version(environment, configuration.frameworks.ogury_core.internal_version, configuration.frameworks.ogury_core.beta_version, configuration.frameworks.ogury_core.release_version)
    ogury_ads_version = get_module_version(environment, configuration.frameworks.ogury_ads.internal_version, configuration.frameworks.ogury_ads.beta_version, configuration.frameworks.ogury_ads.release_version)
    ogury_choice_manager_version = get_module_version(environment, configuration.frameworks.ogury_choice_manager.internal_version, configuration.frameworks.ogury_choice_manager.beta_version, configuration.frameworks.ogury_choice_manager.release_version)

    erb(
      template: "./fastlane/templates/Podfile.erb",
      destination: "./Podfile",
      placeholders: {
        :environment => environment,
        :artifactory_repository_name => artifactory_repository_name,
        :framework_suffix => get_framework_suffix(environment),
        :ogury_core_version => ogury_core_version,
        :ogury_ads_version => ogury_ads_version,
        :ogury_choice_manager_version => ogury_choice_manager_version
      }
      )
  end

desc "test framework for different SDKs"
lane :test do |options|
  if !options[:environment]
    raise "No environment specified!".red
  end

  environment = options[:environment]

    # Install Cocoapods dependencies
    update_internal_cocoapods environment: environment
    generate_podfile environment: environment

    cocoapods(
      podfile: "./Podfile",
      )

    configuration.sdks.tests.each do |sdk|
      test_core_framework(
        configuration: configuration, 
        sdk: sdk
        )

      test_ads_framework(
        configuration: configuration, 
        sdk: sdk
        )

      test_wrapper(
        configuration: configuration, 
        sdk: sdk
        )

      # test_card_framework(
      #   configuration: configuration, 
      #   sdk: sdk
      # )
    end
  end

  lane :deploy_frameworks do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    environment = options[:environment]
    coreTag = options[:coreTag] 
    adsTag = options[:adsTag] 
    adsLibraryTag = options[:adsLibrary] 
    wrapperTag = options[:wrapperTag] 
    artifactory = options[:artifactory] ? options[:artifactory] : false

    if !configuration.allowed_environments.include? environment
      raise "Wrong environment specified!".red
    end

    if coreTag != nil 
      deploy_core_framework(environment: environment, tag: coreTag, artifactory: artifactory)
    end

    if adsTag != nil 
      deploy_ads_framework(environment: environment, tag: adsTag, artifactory: artifactory)
    end

    if adsLibraryTag != nil 
      deploy_adsLibrary_framework(environment: environment, tag: adsLibraryTag, artifactory: artifactory)
    end

    if wrapperTag != nil 
      deploy_wrapper_framework(environment: environment, tag: wrapperTag, artifactory: artifactory)
    end

  end

  desc "Proceed to deploy a new version of a framewok passed as parameter for the specified environment"
  private_lane :deploy_framework do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:tag]
      raise "No tag specified!".red
    end

    if !options[:target]
      raise "No target specified!".red
    end

    environment = options[:environment]
    target = options[:target]
    filePath = target.path
    projectName = target.name
    tag = options[:tag]
    version = get_version(environment, filePath, projectName, tag)
    artifactory = options[:artifactory] ? options[:artifactory] : false

    print "Deploying #{projectName} with version: #{version}\n"

    if !configuration.allowed_environments.include? environment
      raise "Wrong environment specified!".red
    end

    methodName = "prepare_#{target.method}_for_deployment"
    params = {
      configuration: configuration,  
      environment: environment, 
      version: version, 
      tag: tag, 
      artifactory: artifactory
    }

    case environment
    when "devc", "staging", "prod"
      send(methodName, params)
      
      if !options[:dry_run]
        deploy_on_artifactory(configuration: configuration,  environment: environment, version: version, target: target, artifactory: artifactory)
      end

    when "beta", "release"
      send(methodName, params)

      if !options[:dry_run]
        deploy_on_amazon(configuration: configuration, environment: environment, version: version, target: target, artifactory: artifactory)
      end
    end
  end

  desc "Proceed to deploy a new version of a framewok passed as parameter for the specified environment"
  lane :deploy_core_framework do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:tag]
      raise "No tag specified!".red
    end

    environment = options[:environment]
    tag = options[:tag]
    artifactory = options[:artifactory] ? options[:artifactory] : false

    deploy_framework(environment: environment, tag: tag, target: configuration.targets.core, artifactory: artifactory)
  end

  desc "Proceed to deploy a new version of a framewok passed as parameter for the specified environment"
  lane :deploy_ads_framework do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:tag]
      raise "No tag specified!".red
    end

    environment = options[:environment]
    tag = options[:tag]
    artifactory = options[:artifactory] ? options[:artifactory] : false

    deploy_framework(environment: environment, tag: tag, target: configuration.targets.ads, artifactory: artifactory)
  end

  desc "Proceed to deploy a new version of a framewok passed as parameter for the specified environment"
  lane :deploy_adsLibrary_framework do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:tag]
      raise "No tag specified!".red
    end

    environment = options[:environment]
    tag = options[:tag]
    artifactory = options[:artifactory] ? options[:artifactory] : false

    deploy_framework(environment: environment, tag: tag, target: configuration.targets.adsLibrary, artifactory: artifactory)
  end

  desc "Proceed to deploy a new version of a framewok passed as parameter for the specified environment"
  lane :deploy_wrapper_framework do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:tag]
      raise "No tag specified!".red
    end

    environment = options[:environment]
    tag = options[:tag]
    artifactory = options[:artifactory] ? options[:artifactory] : false

    deploy_framework(environment: environment, tag: tag, target: configuration.targets.wrapper, artifactory: artifactory)
  end

  desc "Proceed to deploy a new version of a framewok passed as parameter for the specified environment"
  lane :generate_test_app do |options|
    artifactory = options[:artifactory] ? options[:artifactory] : false
    deploy_test_app(configuration: configuration, artifactory: artifactory)
  end

  desc "Proceed to deploy a new version of the framewok for the specified environment"
  lane :deploy_podspec do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:tag]
      raise "No tag specified!".red
    end

    if !options[:target]
      raise "No target specified!".red
    end

    environment = options[:environment]
    tag = options[:tag]
    target = options[:target]

    if !configuration.allowed_environments.include? environment
      raise "Wrong environment specified!".red
    end

    framework_suffix = get_framework_suffix(environment)

    # Retrieve project version
    version = get_version(environment, configuration.project.file_path, target.publicName, tag)

    case environment
    when "beta"
      # Upload updated Podspec to public Cocoapods repository
      push_to_cocoapods_repository configuration: configuration, framework_suffix: framework_suffix, version: version
    when "release"
      # Upload updated Podspec to Cocoapods trunk
      # TODO: Perform initial release on Cocoapods trunk to obtain CocoaPods authentication token
      # TODO: See https://fuller.li/posts/automated-cocoapods-releases-with-ci on how to automate 'pod trunk push OguryCore.podspec.json' with CocoaPods authentication token
    end
  end

  desc "Proceed to deploy a new version of the core framewok for the specified environment"
  lane :deploy_core_podspec do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:tag]
      raise "No tag specified!".red
    end

    environment = options[:environment]
    tag = options[:tag]
    deploy_podspec(configuration: configuration, tag:tag, target: configuration.targets.core)
  end

  desc "Proceed to deploy a new version of the ads framewok for the specified environment"
  lane :deploy_ads_podspec do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:tag]
      raise "No tag specified!".red
    end

    environment = options[:environment]
    tag = options[:tag]
    deploy_podspec(configuration: configuration, tag:tag, target: configuration.targets.ads)
  end

  desc "Proceed to deploy a new version of the ads framewok for the specified environment"
  lane :deploy_wrapper_podspec do |options|
    if !options[:environment]
      raise "No environment specified!".red
    end

    if !options[:tag]
      raise "No tag specified!".red
    end

    environment = options[:environment]
    tag = options[:tag]
    deploy_podspec(configuration: configuration, tag:tag, target: configuration.targets.wrapper)
  end

end


