  
@Library('ogury-jenkins-lib@v4.0.0') _

pipeline {
    agent {
        label 'macmini-intel'
    }

    environment {
        GIT_TOKEN = credentials('GIT_TOKEN')
        GIT_USERNAME = "weareogury"
        LC_ALL = 'en_US.UTF-8'
        PATH = "/usr/local/bin:~/.rbenv/shims:$PATH"
        RBENV_SHELL = 'bash'
        SONAR_CLOUD_TOKEN = credentials('SONAR_CLOUD_TOKEN')
        ARTIFACTORY_TOKEN = credentials('ARTIFACTORY_TOKEN')
    }

    stages {

        stage('Setup') {
            steps {
                sh """#!/bin/bash -l
                    bundle install
                """
            }
        }

        stage('Build') {
            when {
                beforeAgent true
                not { changeRequest() }
            }

            steps {
                sh """#!/bin/bash -l
                    bundle exec fastlane build
                """
            }
        }

        stage('Test') {
            when {
                beforeAgent true
                changeRequest()
            }
            steps {
                sh """#!/bin/bash -l
                    mkdir -p jenkins
                    ./build-wrapper-macosx-x86 --out-dir jenkins/bw-output bundle exec fastlane test
                """

                sh """#!/bin/bash -l
                    bundle exec fastlane analyse
                """
            }
        }


        stage('Deployment') {
            when {
                beforeAgent true
                buildingTag()
                not { changeRequest() }
            }
            stages {
                stage('Deploy Internal') {
                    when {
                        beforeAgent true
                        tag "internal-*"
                    }
                    steps {
                        sh """#!/bin/bash -l
                            bundle exec fastlane deploy_artefact environment:'devc' tag:${env.TAG_NAME}
                        """

                        sh """#!/bin/bash -l
                            bundle exec fastlane deploy_artefact environment:'staging' tag:${env.TAG_NAME}
                        """

                        sh """#!/bin/bash -l
                            bundle exec fastlane deploy_artefact environment:'prod' tag:${env.TAG_NAME}
                        """
                    }
                }

                stage('Deploy Beta') {
                    environment {
                        GIT_SSH_COMMAND = 'ssh -o StrictHostKeyChecking=no'
                    }
                    when {
                        beforeAgent true
                        tag "beta-*"
                    }
                    steps {
                        sh """#!/bin/bash -l
                            bundle exec fastlane deploy_artefact environment:'beta' tag:${env.TAG_NAME}
                        """

                        withAWS(role:'ci-eu-west-1-macos-jenkins-ci', roleAccount:'556593845588')  {
                            script {
                                s3Utils.uploadDir(
                                    localDir: 'jenkins/output/amazon',
                                    bucket: 'ogury-sdk-binaries',
                                    prefix: ''
                                )
                            }
                        }

                        sshagent(['Ogy-JenkinsAuth']) {
                            sh """#!/bin/bash -l
                                bundle exec fastlane deploy_podspec environment:'beta' tag:${env.TAG_NAME}
                            """
                        }
                    }
                }

                stage('Deploy Release') {
                    environment {
                        GIT_SSH_COMMAND = 'ssh -o StrictHostKeyChecking=no'
                    }
                    when {
                        beforeAgent true
                        tag "release-*"
                    }
                    steps {
                        sh """#!/bin/bash -l
                            bundle exec fastlane deploy_artefact environment:'release' tag:${env.TAG_NAME}
                        """

                        withAWS(role:'ci-eu-west-1-macos-jenkins-ci', roleAccount:'556593845588')  {
                            script {
                                s3Utils.uploadDir(
                                    localDir: 'jenkins/output/amazon',
                                    bucket: 'ogury-sdk-binaries',
                                    prefix: ''
                                )
                            }
                        }

                        sshagent(['Ogy-JenkinsAuth']) {
                            sh """#!/bin/bash -l
                                bundle exec fastlane deploy_podspec environment:'release' tag:${env.TAG_NAME}
                            """
                        }
                    }
                }
            }
        }
    }
}
