##########################
# Required configuration #
##########################

sonar.organization=ogury
sonar.projectKey=Ogury_sdk-core-ios
sonar.projectName=sdk-core-ios
# sonar.projectVersion=3.0.0 # TODO: Move this to Sonar action with automated version assignment with Jenkins
sonar.projectDescription=Core SDK iOS

sonar.host.url=https://sonarcloud.io/
sonar.cfamily.threads=2
sonar.cfamily.cache.enabled=false

sonar.sources=Sources
sonar.tests=Tests

sonar.pullrequest.provider=GitHub
sonar.pullrequest.github.repository=Ogury/sdk-core-ios
 
##########################
# Optional configuration #
##########################

sonar.cfamily.build-wrapper-output=jenkins/bw-output
sonar.sourceEncoding=UTF-8
sonar.coverageReportPaths=jenkins/output/sonarqube-generic-coverage.xml
