  
@Library('ogury-jenkins-lib@v4.0.0') _

pipeline {
    agent {
        label 'macM2-worker'
    }

    environment {
        GIT_TOKEN = credentials('GIT_TOKEN')
        GIT_USERNAME = "weareogury"
        LC_ALL = 'en_US.UTF-8'
        PATH = "/usr/local/bin:~/.rbenv/shims:$PATH"
        RBENV_SHELL = 'zsh'
        SONAR_CLOUD_TOKEN = credentials('SONAR_CLOUD_TOKEN')
        ARTIFACTORY_TOKEN = credentials('ARTIFACTORY_TOKEN')
    }

    stages {

        stage('Setup') {
            steps {
                sh """#!/bin/zsh -l
                    bundle install
                """
            }
        }

        stage('Build') {
            when {
                beforeAgent true
                not { changeRequest() }
            }

            steps {
                sh """#!/bin/zsh -l
                    bundle exec fastlane build environment:prod
                """
            }
        }

        stage('Test-Dev') {
            when {
                beforeAgent true
                changeRequest()
                not {
                    branch 'master'
                }
            }
            steps {
                sh """#!/bin/zsh -l
                    mkdir -p jenkins
                    bundle exec fastlane test environment:prod
                """

                sh """#!/bin/zsh -l
                    bundle exec fastlane analyse
                """
            }
        }

        stage('Test-Prod') {
            when {
                beforeAgent true
                anyOf {
                    branch 'master'
                    changeRequest target:'master'
                }
            }
            steps {
                sh """#!/bin/zsh -l
                    mkdir -p jenkins
                    bundle exec fastlane test environment:release
                """

                sh """#!/bin/zsh -l
                    bundle exec fastlane analyse
                """
            }
        }

        stage('Test Application') {
            environment {
                USER_PASSWORD = credentials('IOS_USER_PASSWORD')
            }
            when {
                beforeAgent true
                tag "test-app-*"
                not { changeRequest() }
            }
            steps {
                // Unlock login.keychain to allow the non-interactive session to access the keychain for signing the App 
                sh """#!/bin/zsh -l
                    security unlock-keychain -p ${USER_PASSWORD} login.keychain
                """

                sh """#!/bin/zsh -l
                    bundle exec fastlane generate_test_app
                """
            }
        }

        stage('Deployment') {
            when {
                beforeAgent true
                buildingTag()
                not { changeRequest() }
            }
            stages {
                stage('Deploy Internal') {
                    when {
                        beforeAgent true
                        tag "internal-*"
                    }
                    steps {

                        sh """#!/bin/zsh -l
                            bundle exec fastlane deploy_artefact environment:prod tag:${env.TAG_NAME}
                        """
                    }
                }

                stage('Deploy Beta') {
                    environment {
                        GIT_SSH_COMMAND = 'ssh -o StrictHostKeyChecking=no'
                    }
                    when {
                        beforeAgent true
                        tag "beta-*"
                    }
                    steps {
                        sh """#!/bin/zsh -l
                            bundle exec fastlane deploy_artefact environment:beta tag:${env.TAG_NAME}
                        """

                        withAWS(role:'ci-eu-west-1-macos-jenkins-ci', roleAccount:'556593845588')  {
                            script {
                                s3Utils.uploadDir(
                                    localDir: 'jenkins/output/amazon',
                                    bucket: 'ogury-sdk-binaries',
                                    prefix: ''
                                )
                            }
                        }

                        sshagent(['Ogy-JenkinsAuth']) {
                            sh """#!/bin/zsh -l
                                bundle exec fastlane deploy_podspec environment:beta tag:${env.TAG_NAME}
                            """
                        }
                    }
                }

                stage('Deploy Release') {
                    environment {
                        GIT_SSH_COMMAND = 'ssh -o StrictHostKeyChecking=no'
                    }
                    when {
                        beforeAgent true
                        tag "release-*"
                    }
                    steps {
                        sh """#!/bin/zsh -l
                            bundle exec fastlane deploy_artefact environment:release tag:${env.TAG_NAME}
                        """

                        withAWS(role:'ci-eu-west-1-macos-jenkins-ci', roleAccount:'556593845588')  {
                            script {
                                s3Utils.uploadDir(
                                    localDir: 'jenkins/output/amazon',
                                    bucket: 'ogury-sdk-binaries',
                                    prefix: ''
                                )
                            }
                        }

                        sshagent(['Ogy-JenkinsAuth']) {
                            sh """#!/bin/zsh -l
                                bundle exec fastlane deploy_podspec environment:release tag:${env.TAG_NAME}
                            """
                        }
                    }
                }
            }
        }
    }
}
