source 'https://cdn.cocoapods.org/'
source 'https://github.com/Ogury/ogury-cocoapods-repository'


plugin 'cocoapods-art', :sources => [
  'sdk-cocoapods-prod',
]


platform :ios, '10.0'

use_frameworks!

workspace 'OguryWrapper'

target 'OguryWrapper' do
  project 'OguryWrapper/OguryWrapper.xcodeproj/'
  
  pod 'OguryCore-Prod', '1.4.1-RC-1.0.7'

  target 'OguryWrapperTests' do
    inherit! :complete

    pod 'OCMock', '~> 3.8.1'
  end
end

target 'OguryWrapperTestApp' do
  project 'OguryWrapperTestApp/OguryWrapperTestApp.xcodeproj'
  
  pod 'OguryCore-Prod', '1.4.1-RC-1.0.7'
  pod 'OguryAds-Prod', '3.7.0-rc-3'
  pod 'OguryChoiceManager-Prod', '4.3.0-rc-2'
end

# Set the OGURY_ENVIRONMENT to match the environment of the dependencies.
post_install do |installer|
  user_projects = installer.aggregate_targets
    .map{|aggregate_target| aggregate_target.user_project}
    .uniq{|project| project}

  user_projects.each do |project|
    project.build_configurations.each do |build_configuration|
      build_configuration.build_settings["OGURY_ENVIRONMENT"] = "prod"
    end

    project.save()
  end
end
