##########################
# Required configuration #
##########################

sonar.organization=ogury
sonar.projectKey=Ogury_sdk-wrapper-ios
sonar.projectName=sdk-wrapper-ios
# sonar.projectVersion=3.0.0 # TODO: Move this to Sonar action with automated version assignment with Jenkins
sonar.projectDescription=Wrapper exposing start method for the Ogury iOS SDK.

sonar.host.url=https://sonarcloud.io/
sonar.cfamily.threads=1

sonar.sources=OguryWrapper/Sources
sonar.tests=OguryWrapper/Tests

##########################
# Optional configuration #
##########################

sonar.cfamily.compile-commands=compilation-database.json
sonar.sourceEncoding=UTF-8
sonar.coverageReportPaths=jenkins/output/sonarqube-generic-coverage.xml
