production:
  environment: "PROD"
  headerBiddingURL: "https://ms-bidder-bidmax-use1.prod.cloud.ogury.io/api/header-bidding-request"
  assetKey: "OGY-669B2C04F486"
  interstitial:
    campaign: "150175"
    adunit: "313076_default"
    creative: ""
    dspCreative: ""
  optin:
    campaign: "150175"
    adunit: "083cddeb-0566-4e74-9a67-2e6401d77338"
    creative: ""
    dspCreative: ""
  thumbnail:
    campaign: "150175"
    adunit: "604b8a5e-1f93-42a7-86f7-5888cc772020"
    creative: ""
    dspCreative: ""
    xOffset: 100
    yOffset: 100
    width: 180
    height: 180
    corner: 0
  mpu:
    campaign: "150175"
    adunit: "9b6dfc65-1123-4f74-9fa9-b96fae449a77"
    creative: ""
    dspCreative: ""
  smallBanner:
    campaign: "150557"
    adunit: "2f823307-c025-490f-8b86-8b9e9c1ca2e9"
    creative: ""
    dspCreative: ""
  headerBiddingInterstitial:
    campaign: ""
    adunit: "86c5fc1c-b49a-458c-8522-a36f4f4c3055_test"
    creative: ""
    dspCreative: ""
  headerBiddingOptin:
    campaign: ""
    adunit: "38f2f7e9-ed8f-431d-b9df-0e9980051f56_test"
    creative: ""
    dspCreative: ""
  headerBiddingMpu:
    campaign: ""
    adunit: "d802af6d-a376-4355-8810-ef6b27645e0a_test"
    creative: ""
    dspCreative: ""
  headerBiddingSmallBanner:
    campaign: ""
    adunit: "02b21b7d-7a1d-4b1d-b32c-7c3a8c5d598b_test"
    creative: ""
    dspCreative: ""
staging:
  environment: "STAGING"
  headerBiddingURL: "https://ms-bidder-bidmax.staging.cloud.ogury.io/api/header-bidding-request"
  assetKey: "OGY-18980EAC7424"
  interstitial:
    campaign: "35993"
    adunit: "272810_default"
    creative: ""
    dspCreative: ""
  optin:
    campaign: "35993"
    adunit: "9bf9844a-f7ed-4af8-b472-42fd13a043f2"
    creative: ""
    dspCreative: ""
  thumbnail:
    campaign: "35995"
    adunit: "3deaf060-2193-4b5e-82b3-1c6b0580dee2"
    creative: ""
    dspCreative: ""
    xOffset: 100
    yOffset: 100
    width: 180
    height: 180
    corner: 0
  mpu:
    campaign: "35996"
    adunit: "467063de-7e47-4593-a2b3-d8d9b6767427"
    creative: ""
    dspCreative: ""
  smallBanner:
    campaign: "35997"
    adunit: "71832c73-6628-423a-a000-f60f37fa9d3b"
    creative: ""
    dspCreative: ""
  headerBiddingInterstitial:
    campaign: ""
    adunit: "a392f8a3-e3c8-4db2-ba51-6c6550cf24ef"
    creative: ""
    dspCreative: ""
  headerBiddingOptin:
    campaign: ""
    adunit: "a9214ff2-822d-47bd-bc06-2eee7550a4f1"
    creative: ""
    dspCreative: ""
  headerBiddingMpu:
    campaign: ""
    adunit: "d3781bf4-5848-4fcf-a599-cb28f23874bc"
    creative: ""
    dspCreative: ""
  headerBiddingSmallBanner:
    campaign: ""
    adunit: "201b40fc-94d3-42ce-93ec-930b7194304c"
    creative: ""
    dspCreative: ""
devc:
  environment: "DEVC"
  headerBiddingURL: "https://ms-bidder-bidmax.devc.cloud.ogury.io/api/header-bidding-request"
  assetKey: "OGY-F9104A3FEDA2"
  interstitial:
    campaign: "32645"
    adunit: "272481_default"
    creative: ""
    dspCreative: ""
  optin:
    campaign: ""
    adunit: "7792c3be-024f-4dce-8ff0-18b1cb8b88b3"
    creative: ""
    dspCreative: ""
  thumbnail:
    campaign: "31482"
    adunit: "7a9d1387-6f61-42b2-ad5f-5038491bc840"
    creative: ""
    dspCreative: ""
    xOffset: 100
    yOffset: 100
    width: 180
    height: 180
    corner: 0
  mpu:
    campaign: ""
    adunit: "2565618c-e2f3-4623-bc78-c48590c9f9eb"
    creative: ""
    dspCreative: ""
  smallBanner:
    campaign: ""
    adunit: "26e7671e-ae14-4b71-b540-8e67087ef705"
    creative: ""
    dspCreative: ""
  headerBiddingInterstitial:
    campaign: ""
    adunit: "a392f8a3-e3c8-4db2-ba51-6c6550cf24ef"
    creative: ""
    dspCreative: ""
  headerBiddingOptin:
    campaign: ""
    adunit: "a9214ff2-822d-47bd-bc06-2eee7550a4f1"
    creative: ""
    dspCreative: ""
  headerBiddingMpu:
    campaign: ""
    adunit: "d3781bf4-5848-4fcf-a599-cb28f23874bc"
    creative: ""
    dspCreative: ""
  headerBiddingSmallBanner:
    campaign: ""
    adunit: "201b40fc-94d3-42ce-93ec-930b7194304c"
    creative: ""
    dspCreative: ""
  
